on: release
name: Handle Release
jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master
    - name: Generate the artifacts
      uses: LabMarket/github-action-build@master
    - name: Upload
      uses: LabMarket/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: roach-*
